### ISSUE TITLE
I'd like to adopt the Vkontakte strategy

### ISSUE THREAD

**Issue by mamantoha** [omniauth/omniauth-contrib#2]

**Comment by ivanovv** [comment]
In your Gemfile
`gem 'omniauth-contrib', :git => 'https://github.com/intridea/omniauth-contrib.git'`

and in config/initializers/omniauth.rb:

`Rails.application.config.middleware.use OmniAuth::Builder do
  provider :vkontakte, 'API Key', 'Secret Key', {:client_options => {:ssl => {:ca_path => "/etc/ssl/certs"}}}
end`

and you are good to go.

When the gem is released
`gem 'omniauth-contrib'`
will be enough.

**Comment by mamantoha** [comment]
i'd like to be the official maintainer of a gem for Vkontakte strategy and support its future updates.
https://github.com/mamantoha/omniauth-vkontakte

**Comment by ivanovv** [comment]
Well, as the [Adapting strategies for 1.0](https://github.com/intridea/omniauth/wiki/Adapting-strategies-for-1.0) states in its **Packaging step**, gem needs a set of tests, and your code has no test (and it has some other issues, i commented on them). Besides tests, it also lacks some information that Vkontakte provides about its users, like city and country, and that the original [code](https://github.com/german/omniauth/blob/master/oa-oauth/lib/omniauth/strategies/vkontakte.rb) from [german](https://github.com/german) had.
Until your gem is feature rich I think omniauth-contrib is enough. When your gem is mature enough it can be used as an officail strategy for OmniAuth
